/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'erik' at '7/6/16 10:55 AM' with Gradle 2.14
 *
 * @author erik, @date 7/6/16 10:55 AM
 */
public class Library
{
	public boolean someLibraryMethod()
	{
		return true;
	}
}
