import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import static org.testng.AssertJUnit.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'erik' at '7/6/16 10:55 AM' with Gradle 2.14
 *
 * @author erik, @date 7/6/16 10:55 AM
 */
public class LibraryTest
{
	//This method will provide data to any test method that declares that its Data Provider is named "test1"
	@DataProvider(name = "test1")
	public Object[][] createData1()
	{
		return new Object[][]{
				{"Cedric", new Integer(36)}, {"Anne", new Integer(37)},
				};
	}

	@Test
	public void testSomeLibraryMethod()
	{
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}

	//This test method declares that its data should be supplied by the Data Provider named "test1"
	@Test(dataProvider = "test1")
	public void verifyData1(String n1, Integer n2)
	{
		System.out.println(n1 + " " + n2);
	}
}
